# Default values for mininet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: andybavier/mininet
  tag: 1.0.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

topo: topo.py
numIntfs: 2
onosOpenflowService: onos-openflow.default.svc.cluster.local

bandwidthManagement: false

podSecurityContext: {}

securityContext:
  privileged: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
