# Default values for free5gc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  dbUri: mongodb://mongo.default.svc.cluster.local/free5gc
  enableMininet: false

amf:
  s1ap:
    addr: 192.168.2.2

smf:
  pfcp:
    addr: 192.168.2.4
  http:
    addr: 192.168.2.4

upf:
  pfcp:
    addr: 192.168.2.6
  gtpu:
    subnet: 192.168.2.0/24
    addr: 192.168.2.6
