# in free5gc chart
amf:
  s1ap:
    addr: 192.168.2.2

smf:
  pfcp:
    addr: 192.168.2.4
  http:
    addr: 192.168.2.4

upf:
  pfcp:
    addr: 192.168.2.6
  gtpu:
    subnet: 192.168.4.0/24
    addr: 192.168.4.2

# in free5gc and mininet chart
enableMininet: true

# in mininet and onos chart
bandwidthManagement: false
