apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: mn-enb-bridge-conf
spec:
  config: '{
    "name": "mn1",
    "type": "bridge",
    "bridge": "mn1",
    "isDefaultGateway": true,
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.4.0/24",
      "rangeStart": "192.168.4.3",
      "rangeEnd": "192.168.4.254",
      "gateway": "192.168.4.1"
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: mn-upf-bridge-conf
spec:
  config: '{
    "name": "mn2",
    "type": "bridge",
    "bridge": "mn2",
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.4.0/24",
      "rangeStart": "192.168.4.3",
      "rangeEnd": "192.168.4.254"
    }
  }'
