apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-deployment
  labels:
    app: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: steven30801/free5gc-webui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: ui
              containerPort: 3000
              hostPort: 3000
          env:
            - name: DB_URI
              value: mongodb://mongo-service.default.svc.cluster.local/free5gc
