# Default values for upf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: steven30801/free5gc-build
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

pfcp:
  addr: 192.168.2.6
gtpu:
  subnet: 192.168.2.0/24
  addr: 192.168.2.6

enableMininet: false

podSecurityContext: {}

securityContext: 
  privileged: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
