apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.dbServiceType }}
  ports:
    - name: db
{{ toYaml .Values.service.db | indent 6 }}
  selector:
    {{- include "mongo.selectorLabels" . | nindent 4 }}
